In [31]:
! pip install -r requirements.txt

Requirement already satisfied: numpy in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from -r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: pandas in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from -r requirements.txt (line 2)) (2.3.3)
Collecting scikit-learn (from -r requirements.txt (line 3))
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting matplotlib (from -r requirements.txt (line 4))
  Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting seaborn (from -r requirements.txt (line 5))
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: ucimlrepo in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from -r requirements.txt (line 6)) (0.0.7)
Collecting imbalanced-learn (from -r requirements.txt (line 7))
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Collecting xgboost (from -r requirements.txt (line 8))
  Downloading xgboost-3.1.2-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.3)
Collecting scipy>=1.10.0 (from scikit-learn->-r requirements.txt (line 3))
  Downloading scipy-1.16.3-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn->-r requirements.txt (line 3))
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn->-r requirements.txt (line 3))
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements.txt (line 4))
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 4))
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->-r requirements.txt (line 4))
  Downloading fonttools-4.61.1-cp314-cp314-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->-r requirements.txt (line 4))
  Downloading kiwisolver-1.4.9-cp314-cp314-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (25.0)
Collecting pillow>=8 (from matplotlib->-r requirements.txt (line 4))
  Downloading pillow-12.1.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib->-r requirements.txt (line 4))
  Downloading pyparsing-3.3.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from ucimlrepo->-r requirements.txt (line 6)) (2026.1.4)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn->-r requirements.txt (line 7))
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\documents\github\applied-statistical-learning-projet-\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------ --------------------------- 2.6/8.1 MB 13.4 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 16.2 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 15.6 MB/s  0:00:00
Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ------------------------ --------------- 5.0/8.3 MB 24.4 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 19.6 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.16.3-cp314-cp314-win_amd64.whl (39.4 MB)
   ---------------------------------------- 0.0/39.4 MB ? eta -:--:--
   ---- ----------------------------------- 4.7/39.4 MB 23.8 MB/s eta 0:00:02
   ---------- ----------------------------- 10.0/39.4 MB 23.7 MB/s eta 0:00:02
   ----------------- ---------------------- 16.8/39.4 MB 26.1 MB/s eta 0:00:01
   ----------------------- ---------------- 23.1/39.4 MB 26.9 MB/s eta 0:00:01
   ------------------------------ --------- 30.1/39.4 MB 28.1 MB/s eta 0:00:01
   ----------------------------------- ---- 35.1/39.4 MB 27.4 MB/s eta 0:00:01
   ---------------------------------------  39.3/39.4 MB 26.8 MB/s eta 0:00:01
   ---------------------------------------- 39.4/39.4 MB 24.1 MB/s  0:00:01
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading xgboost-3.1.2-py3-none-win_amd64.whl (72.0 MB)
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   --- ------------------------------------ 5.8/72.0 MB 28.6 MB/s eta 0:00:03
   ------ --------------------------------- 12.1/72.0 MB 28.4 MB/s eta 0:00:03
   ---------- ----------------------------- 18.6/72.0 MB 29.4 MB/s eta 0:00:02
   ------------- -------------------------- 24.9/72.0 MB 29.0 MB/s eta 0:00:02
   ----------------- ---------------------- 31.7/72.0 MB 29.4 MB/s eta 0:00:02
   --------------------- ------------------ 38.8/72.0 MB 30.0 MB/s eta 0:00:02
   ---------------------- ----------------- 40.9/72.0 MB 29.2 MB/s eta 0:00:02
   ---------------------- ----------------- 40.9/72.0 MB 29.2 MB/s eta 0:00:02
   ---------------------- ----------------- 41.2/72.0 MB 21.8 MB/s eta 0:00:02
   ------------------------ --------------- 44.0/72.0 MB 20.6 MB/s eta 0:00:02
   -------------------------- ------------- 48.0/72.0 MB 20.4 MB/s eta 0:00:02
   ----------------------------- ---------- 53.0/72.0 MB 20.7 MB/s eta 0:00:01
   -------------------------------- ------- 59.0/72.0 MB 21.3 MB/s eta 0:00:01
   ---------------------------------- ----- 62.1/72.0 MB 20.8 MB/s eta 0:00:01
   ------------------------------------- -- 67.4/72.0 MB 21.1 MB/s eta 0:00:01
   ---------------------------------------  71.8/72.0 MB 21.3 MB/s eta 0:00:01
   ---------------------------------------  71.8/72.0 MB 21.3 MB/s eta 0:00:01
   ---------------------------------------- 72.0/72.0 MB 19.9 MB/s  0:00:03
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 16.1 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.1.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ------------------------------ --------- 5.5/7.2 MB 26.0 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 23.0 MB/s  0:00:00
Downloading pyparsing-3.3.1-py3-none-any.whl (121 kB)
Installing collected packages: threadpoolctl, scipy, pyparsing, pillow, kiwisolver, joblib, fonttools, cycler, contourpy, xgboost, scikit-learn, matplotlib, sklearn-compat, seaborn, imbalanced-learn

   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]
   -- -------------------------------------  1/15 [scipy]

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

### Importation des bibliothèques

In [33]:
import numpy as np 
import pandas as pd
from ucimlrepo import fetch_ucirepo

### Importation de la base

In [34]:
  
# fetch dataset 
cdc_diabetes_health_indicators = fetch_ucirepo(id=891) 
  
# data (as pandas dataframes) 
X = cdc_diabetes_health_indicators.data.features  ## Il s'agit de tous les features de la base
y = cdc_diabetes_health_indicators.data.targets   ## Il s'agit de la variable cible (avoir le diabète ou pas)

### Visualisation des metadonnées

In [35]:
pd.set_option("display.max_colwidth", None)
vars_meta = cdc_diabetes_health_indicators.variables
vars_meta[["name", "type", "description"]]

,name,type,description
0,ID,Integer,Patient ID
1,Diabetes_binary,Binary,0 = no diabetes 1 = prediabetes or diabetes
2,HighBP,Binary,0 = no high BP 1 = high BP
3,HighChol,Binary,0 = no high cholesterol 1 = high cholesterol
4,CholCheck,Binary,0 = no cholesterol check in 5 years 1 = yes cholesterol check in 5 years
5,BMI,Integer,Body Mass Index
6,Smoker,Binary,Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes] 0 = no 1 = yes
7,Stroke,Binary,(Ever told) you had a stroke. 0 = no 1 = yes
8,HeartDiseaseorAttack,Binary,coronary heart disease (CHD) or myocardial infarction (MI) 0 = no 1 = yes
9,PhysActivity,Binary,physical activity in past 30 days - not including job 0 = no 1 = yes
10,Fruits,Binary,Consume Fruit 1 or more times per day 0 = no 1 = yes
11,Veggies,Binary,Consume Vegetables 1 or more times per day 0 = no 1 = yes
12,HvyAlcoholConsump,Binary,Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) 0 = no 1 = yes
13,AnyHealthcare,Binary,"Have any kind of health care coverage, including health insurance, prepaid plans such as HMO, etc. 0 = no 1 = yes"
14,NoDocbcCost,Binary,Was there a time in the past 12 months when you needed to see a doctor but could not because of cost? 0 = no 1 = yes
15,GenHlth,Integer,Would you say that in general your health is: scale 1-5 1 = excellent 2 = very good 3 = good 4 = fair 5 = poor
16,MentHlth,Integer,"Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good? scale 1-30 days"
17,PhysHlth,Integer,"Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good? scale 1-30 days"
18,DiffWalk,Binary,Do you have serious difficulty walking or climbing stairs? 0 = no 1 = yes
19,Sex,Binary,0 = female 1 = male
20,Age,Integer,13-level age category (_AGEG5YR see codebook) 1 = 18-24 9 = 60-64 13 = 80 or older
21,Education,Integer,Education level (EDUCA see codebook) scale 1-6 1 = Never attended school or only kindergarten 2 = Grades 1 through 8 (Elementary) 3 = Grades 9 through 11 (Some high school) 4 = Grade 12 or GED (High school graduate) 5 = College 1 year to 3 years (Some college or technical school) 6 = College 4 years or more (College graduate)
22,Income,Integer,"Income scale (INCOME2 see codebook) scale 1-8 1 = less than $10,000 5 = less than $35,000 8 = $75,000 or more"

In [3]:
X.head()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1,1,1,40,1,0,0,0,0,1,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,25,1,0,0,1,0,0,...,0,1,3,0,0,0,0,7,6,1
2,1,1,1,28,0,0,0,0,1,0,...,1,1,5,30,30,1,0,9,4,8
3,1,0,1,27,0,0,0,1,1,1,...,1,0,2,0,0,0,0,11,3,6
4,1,1,1,24,0,0,0,1,1,1,...,1,0,2,3,0,0,0,11,5,4

In [4]:
y.describe()

       Diabetes_binary
count    253680.000000
mean          0.139333
std           0.346294
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000

In [ ]:
# Ajout de la cible y à X 
X['Diabetes_binary'] = y['Diabetes_binary'].values
X.head()

C:\Users\user\AppData\Local\Temp\ipykernel_22740\679768990.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Diabetes_binary'] = y['Diabetes_binary'].values

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Diabetes_binary
0,1,1,1,40,1,0,0,0,0,1,...,0,5,18,15,1,0,9,4,3,0
1,0,0,0,25,1,0,0,1,0,0,...,1,3,0,0,0,0,7,6,1,0
2,1,1,1,28,0,0,0,0,1,0,...,1,5,30,30,1,0,9,4,8,0
3,1,0,1,27,0,0,0,1,1,1,...,0,2,0,0,0,0,11,3,6,0
4,1,1,1,24,0,0,0,1,1,1,...,0,2,3,0,0,0,11,5,4,0

In [6]:
X.describe()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Diabetes_binary
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,0.811420,...,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875,0.139333
std,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,0.391175,...,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148,0.346294
min,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000,0.000000
50%,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000,0.000000
75%,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000,0.000000
max,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000,1.000000

##  Exploration de la base de données

In [8]:
X.shape

(253680, 22)

La base contient 253680 observations dont 22 colonnes (y compris la cible).

In [10]:
X["Diabetes_binary"].value_counts()

Diabetes_binary
0    218334
1     35346
Name: count, dtype: int64

In [12]:
X["Diabetes_binary"].value_counts(normalize=True) * 100

Diabetes_binary
0    86.066698
1    13.933302
Name: proportion, dtype: float64

La répartition des modalités de la variable cible est très déséquilibrée. Seulement 14% des individus sont diabétiques pour 86% qui ne le sont pas. Nous verrons plus loin comment nous exploitons les données pour faire face à cela.

In [13]:
X.isna().sum()

HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
Diabetes_binary         0
dtype: int64

Aucune valeur manquante détectée

In [16]:
np.isinf(X).sum()

HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
Diabetes_binary         0
dtype: int64

In [17]:
X.duplicated().sum()

np.int64(24206)

On a là 24206 doublons. A priori il s'agt d'observations dupliquées correspondant à des individus distincts. Elles seront donc conservées afin de préserver la distribution empirique des données et d’éviter l’introduction d’un biais artificiel.

In [ ]:
## Quelques doublons

X[X.duplicated(keep=False)].sort_values(by=X.columns.tolist())

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Diabetes_binary
4517,0,0,0,17,0,0,0,1,1,1,...,0,1,0,0,0,0,8,6,8,0
207307,0,0,0,17,0,0,0,1,1,1,...,0,1,0,0,0,0,8,6,8,0
42369,0,0,0,18,0,0,0,1,1,1,...,0,1,0,0,0,0,10,6,8,0
108949,0,0,0,18,0,0,0,1,1,1,...,0,1,0,0,0,0,10,6,8,0
17475,0,0,0,19,0,0,0,1,1,1,...,0,1,0,0,0,0,4,6,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246364,1,1,1,40,0,0,0,1,1,1,...,0,2,0,0,0,0,9,6,7,0
99426,1,1,1,40,0,0,0,1,1,1,...,0,3,0,0,0,0,9,6,7,0
157792,1,1,1,40,0,0,0,1,1,1,...,0,3,0,0,0,0,9,6,7,0
41565,1,1,1,43,0,0,0,1,0,1,...,0,3,0,0,0,0,8,6,8,0
79564,1,1,1,43,0,0,0,1,0,1,...,0,3,0,0,0,0,8,6,8,0

### Modalités de chaque variable

In [21]:
for col in X.columns:
    print(col, ":", sorted(X[col].dropna().unique()))

HighBP : [np.int64(0), np.int64(1)]
HighChol : [np.int64(0), np.int64(1)]
CholCheck : [np.int64(0), np.int64(1)]
BMI : [np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(92), np.int64(95), np.int64(96), np.int64(98)]
Smoker : [np.int64(0), np.int64(1)]
Stroke : [np.int64(0), np.int64(1)]
HeartDiseaseorAttack : [np.int64(0), np.int64(1)]
PhysActivity : [np.int64(0), np.int64(1)]
Fruits : [np.int64(0), np.int64(1)]
Veggies : [np.int64(0), np.int64(1)]
HvyAlcoholConsump : [np.int64(0), np.int64(1)]
AnyHealthcare : [np.int64(0), np.int64(1)]
NoDocbcCost : [np.int64(0), np.int64(1)]
GenHlth : [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
MentHlth : [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30)]
PhysHlth : [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30)]
DiffWalk : [np.int64(0), np.int64(1)]
Sex : [np.int64(0), np.int64(1)]
Age : [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13)]
Education : [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
Income : [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]
Diabetes_binary : [np.int64(0), np.int64(1)]

Les variables sont toutes numériques. Certaines variables multimodales comme education, age, income sont ordonnées. Donc nous avons jugé qu'il n'y a pas de raison de les diviser avec le One-hot incoder.